/* Busca por todos os campos dos registros */
SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_PRODUTOS;

/* Busca por campos especificos */
SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO,
VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT CPF, NOME, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT IDADE, CPF, NOME, DATA_NASCIMENTO
FROM TB_CLIENTES;

/* Apelido de campos */
SELECT CPF AS CPF_DO_CLIENTE, NOME AS NOME_DO_CLIENTE, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT NOME, MATRICULA FROM TB_VENDEDORES;

/* Filtragem de registros com o where */
SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1037797';

SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Cítricos';

UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_VENDEDORES WHERE NOME = 'Cláudia Morais';

/* Explorando as possibilidades com o where */
SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_CLIENTES WHERE IDADE = 22;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22;
SELECT * FROM TB_CLIENTES WHERE IDADE < 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;
SELECT * FROM TB_CLIENTES WHERE NOME = 'Fernando Cavalcante';
SELECT * FROM TB_CLIENTES WHERE NOME <> 'Fernando Cavalcante';
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA <> 16.008;
SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.1;

/* Filtragem de datas */
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('07/10/1995', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO > TO_DATE('07/10/1995', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO < TO_DATE('07/10/1995', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 10;
SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;
SELECT * FROM TB_VENDEDORES WHERE TO_CHAR(DATA_ADMISSAO, 'YYYY') >= 2016;

/* Filtragem com AND e OR*/
SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.007;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16 AND PRECO_LISTA <= 21;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22 AND SEXO = 'F';
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
SELECT * FROM TB_CLIENTES WHERE (IDADE > 22 AND SEXO = 'F') AND (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');
SELECT * FROM TB_VENDEDORES WHERE DE_FERIAS = 'sim' AND TO_CHAR(DATA_ADMISSAO, 'YYYY') < 2016;