/* Alterações na tabela de vendedores */
ALTER TABLE TB_VENDEDORES ADD DATA_ADMISSAO DATE;
ALTER TABLE TB_VENDEDORES ADD DE_FERIAS VARCHAR2(3);

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);

INSERT INTO TB_VENDEDORES VALUES
(00235, 'Márcio Almeida Silva', 8, TO_DATE('15/08/2014','DD/MM/YYYY'), 'nao');

INSERT INTO TB_VENDEDORES VALUES
(00236, 'Cláudia Morais', 8, TO_DATE('17/09/2013','DD/MM/YYYY'), 'sim');

INSERT INTO TB_VENDEDORES VALUES
(00237, 'Roberta Martins', 11, TO_DATE('18/03/2017','DD/MM/YYYY'), 'sim');

INSERT INTO TB_VENDEDORES VALUES
(00238, 'Péricles Alves', 11, TO_DATE('21/08/2016','DD/MM/YYYY'), 'nao');

SELECT * FROM TB_VENDEDORES;